Repository vmware-tanzu/secrets-manager, pull requests merged in 2023-09, with the labels that each got.

#232 190: Fixing sentinal and safe's identify yaml
  helm-charts/0.21.0/charts/safe/templates/identity.yaml
  helm-charts/0.21.0/charts/safe/values.yaml
  helm-charts/0.21.0/charts/sentinel/values.yaml
Labels: feature:helm-charts

#235 Update blog navigation
  README.md
  docs/README.md
  docs/_includes/body-blog.html
  docs/_includes/toc-date.html
  docs/_includes/toc-page.html
  docs/_layouts/blog-home.html
  docs/_layouts/blog.html
  docs/_layouts/post.html
  docs/_pages/0000-community.md
  docs/_pages/0005-blog.md
  docs/_pages/0130-contributing.md
  docs/_pages/0250-showcase.md
  docs/_pages/0980-release-management.md
  docs/_posts/2023-08-15-keep-your-secrets.md
  docs/assets/gitbook/custom.css
Labels: dco-required

#238 190: Adding variables in ClusterSPIFFEID identity for sentinel
  helm-charts/0.21.0/charts/sentinel/templates/identity.yaml
Labels: bug

#247 #246: Introducing script to automate helm-chart release for a given version
  helm-charts/init_next_helm_chart.sh
  helm-charts/release_helm_chart.sh
Labels: enhancement, feature:helm-charts

#253 Minor fix to helm-chart automate script
  helm-charts/init_next_helm_chart.sh
  helm-charts/release_helm_chart.sh
Labels: enhancement

#255 Introducing initial helm-chart for version 0.22.0
  helm-charts/0.22.0/Chart.yaml
  helm-charts/0.22.0/README.md
  helm-charts/0.22.0/charts/safe/.helmignore
  helm-charts/0.22.0/charts/safe/Chart.yaml
  helm-charts/0.22.0/charts/safe/templates/Deployment.yaml
  helm-charts/0.22.0/charts/safe/templates/_helpers.tpl
  helm-charts/0.22.0/charts/safe/templates/hook-preinstall_role.yaml
  helm-charts/0.22.0/charts/safe/templates/identity.yaml
  helm-charts/0.22.0/charts/safe/templates/role_binding.yaml
  helm-charts/0.22.0/charts/safe/templates/secret.yaml
  helm-charts/0.22.0/charts/safe/templates/service.yaml
  helm-charts/0.22.0/charts/safe/templates/serviceaccount.yaml
  helm-charts/0.22.0/charts/safe/templates/tests/test-connection.yaml
  helm-charts/0.22.0/charts/safe/values.yaml
  helm-charts/0.22.0/charts/sentinel/.helmignore
  helm-charts/0.22.0/charts/sentinel/Chart.yaml
  helm-charts/0.22.0/charts/sentinel/templates/Deployment.yaml
  helm-charts/0.22.0/charts/sentinel/templates/_helpers.tpl
  helm-charts/0.22.0/charts/sentinel/templates/identity.yaml
  helm-charts/0.22.0/charts/sentinel/templates/serviceaccount.yaml
  helm-charts/0.22.0/charts/sentinel/values.yaml
  helm-charts/0.22.0/charts/spire/.helmignore
  helm-charts/0.22.0/charts/spire/Chart.yaml
  helm-charts/0.22.0/charts/spire/templates/_helpers.tpl
  helm-charts/0.22.0/charts/spire/templates/crd-rbac/hook-preinstall_leader_election_role.yaml
  helm-charts/0.22.0/charts/spire/templates/crd-rbac/hook-preinstall_role.yaml
  helm-charts/0.22.0/charts/spire/templates/crd-rbac/leader_election_role_binding.yaml
  helm-charts/0.22.0/charts/spire/templates/crd-rbac/role_binding.yaml
  helm-charts/0.22.0/charts/spire/templates/hook-preinstall_spiffe-csi-driver.yaml
  helm-charts/0.22.0/charts/spire/templates/hook-preinstall_spire-namespace.yaml
  helm-charts/0.22.0/charts/spire/templates/spire-agent.yaml
  helm-charts/0.22.0/charts/spire/templates/spire-controller-manager-config.yaml
  helm-charts/0.22.0/charts/spire/templates/spire-controller-manager-webhook.yaml
  helm-charts/0.22.0/charts/spire/templates/spire-server.yaml
  helm-charts/0.22.0/charts/spire/values.yaml
  helm-charts/0.22.0/crds/spire.spiffe.io_clusterfederatedtrustdomains.yaml
  helm-charts/0.22.0/crds/spire.spiffe.io_clusterspiffeids.yaml
  helm-charts/0.22.0/crds/spire.spiffe.io_clusterstaticentries.yaml
  helm-charts/0.22.0/templates/hook-preinstall-namespace.yaml
  helm-charts/0.22.0/values.yaml
Labels: feature:helm-charts

#260 Adding support to sign commit for automated commit scripts
  helm-charts/init_next_helm_chart.sh
  helm-charts/release_helm_chart.sh
Labels: enhancement

#261 Releasing helm-chart for version 0.21.0
  index.yaml
  vsecm-0.21.0.tgz
Labels: feature:helm-charts

#262 252: Upgrading golang version to 1.21
  go.mod
  go.sum
Labels: enhancement

#265 Feature/add
  MAINTAINERS.md
Labels: dco-required

#274 269: Updating release-management to include helm-chart release and initialisation process
  docs/_pages/0980-release-management.md
  helm-charts/0.22.0/charts/safe/templates/deployment.yaml
  helm-charts/0.22.0/charts/safe/values.yaml
Labels: documentation

#276 Updating uninstall script with additional resource needs to be clean during uninstall of VSecM
  hack/uninstall.sh
Labels: enhancement

#275 155: Updating helm-chart and k8s manifests with latest SPIRE images
  helm-charts/0.22.0/values.yaml
  k8s/spire/spire/spire-agent.yaml
  k8s/spire/spire/spire-server.yaml
Labels: enhancement, SPIRE

#279 277: Adding unit-tests for core/env package
  core/env/endpoint_test.go
  core/env/init_test.go
  core/env/logging_test.go
  core/env/poll_test.go
  core/env/probe_test.go
  core/env/safe_test.go
  core/env/sidecar_test.go
  core/env/spiffe_test.go
  core/env/svid_test.go
  core/env/tls_test.go
Labels: quality

#278 Introducing unit-test cases for core pacakges
  core/audit/audit_test.go
  core/crypto/crypto.go
  core/crypto/crypto_test.go
  core/entity/data/v1/v1.go
  core/entity/data/v1/v1_test.go
Labels: quality

#280 277: Adding unit test cases for log, probe and template packages
  core/log/log_test.go
  core/probe/privates_test.go
  core/template/template.go
  core/template/template_test.go
  core/validation/validation_test.go
Labels: quality
