Repository vmware-tanzu/secrets-manager, pull requests merged in 2023-12, with the labels that each got.

#339 Ovolkan/gh pages
  index.yaml
Labels: dco-required

#350 documentation update
  core/env/endpoint.go
  core/env/svid.go
  core/validation/validation.go
  docs/_pages/0110-configuration.md
  makefiles/VSecMHelp.mk
Labels: dco-required

#344 Introducing initial helm-chart for version 0.21.5
  helm-charts/0.21.5/Chart.yaml
  helm-charts/0.21.5/README.md
  helm-charts/0.21.5/charts/safe/.helmignore
  helm-charts/0.21.5/charts/safe/Chart.yaml
  helm-charts/0.21.5/charts/safe/templates/Deployment.yaml
  helm-charts/0.21.5/charts/safe/templates/_helpers.tpl
  helm-charts/0.21.5/charts/safe/templates/hook-preinstall_role.yaml
  helm-charts/0.21.5/charts/safe/templates/identity.yaml
  helm-charts/0.21.5/charts/safe/templates/role_binding.yaml
  helm-charts/0.21.5/charts/safe/templates/secret.yaml
  helm-charts/0.21.5/charts/safe/templates/service.yaml
  helm-charts/0.21.5/charts/safe/templates/serviceaccount.yaml
  helm-charts/0.21.5/charts/safe/values.yaml
  helm-charts/0.21.5/charts/sentinel/.helmignore
  helm-charts/0.21.5/charts/sentinel/Chart.yaml
  helm-charts/0.21.5/charts/sentinel/templates/Deployment.yaml
  helm-charts/0.21.5/charts/sentinel/templates/_helpers.tpl
  helm-charts/0.21.5/charts/sentinel/templates/identity.yaml
  helm-charts/0.21.5/charts/sentinel/templates/serviceaccount.yaml
  helm-charts/0.21.5/charts/sentinel/values.yaml
  helm-charts/0.21.5/charts/spire/.helmignore
  helm-charts/0.21.5/charts/spire/Chart.yaml
  helm-charts/0.21.5/charts/spire/templates/_helpers.tpl
  helm-charts/0.21.5/charts/spire/templates/crd-rbac/hook-preinstall_leader_election_role.yaml
  helm-charts/0.21.5/charts/spire/templates/crd-rbac/hook-preinstall_role.yaml
  helm-charts/0.21.5/charts/spire/templates/crd-rbac/leader_election_role_binding.yaml
  helm-charts/0.21.5/charts/spire/templates/crd-rbac/role_binding.yaml
  helm-charts/0.21.5/charts/spire/templates/hook-preinstall_spiffe-csi-driver.yaml
  helm-charts/0.21.5/charts/spire/templates/hook-preinstall_spire-namespace.yaml
  helm-charts/0.21.5/charts/spire/templates/spire-agent.yaml
  helm-charts/0.21.5/charts/spire/templates/spire-controller-manager-config.yaml
  helm-charts/0.21.5/charts/spire/templates/spire-controller-manager-webhook.yaml
  helm-charts/0.21.5/charts/spire/templates/spire-server.yaml
  helm-charts/0.21.5/charts/spire/values.yaml
  helm-charts/0.21.5/crds/spire.spiffe.io_clusterfederatedtrustdomains.yaml
  helm-charts/0.21.5/crds/spire.spiffe.io_clusterspiffeids.yaml
  helm-charts/0.21.5/crds/spire.spiffe.io_clusterstaticentries.yaml
  helm-charts/0.21.5/templates/hook-preinstall-namespace.yaml
  helm-charts/0.21.5/values.yaml
Labels: feature:helm-charts

#362 doc update
  docs/_pages/0980-release-management.md
Labels: dco-required

#373 Simplifying k8s manifests directory, this will allow to use existing deploy spire and install vsecm alone using k8s manifests
  Makefile
  hack/tag-docker.sh
  hack/update-k8s-manifests.sh
  helm-charts/0.21.4/README.md
  helm-charts/0.21.5/README.md
  helm-charts/0.21.6/charts/safe/templates/hook-preinstall-namespace.yaml
  helm-charts/0.21.6/values.yaml
  helm-charts/0.22.0/README.md
  k8s/0.21.6/0.21.6-local-distroless-fips.yaml
  k8s/0.21.6/0.21.6-local-distroless.yaml
  k8s/0.21.6/0.21.6-local-photon-fips.yaml
  k8s/0.21.6/0.21.6-local-photon.yaml
  k8s/0.21.6/0.21.6-remote-distroless.yaml
  k8s/0.21.6/0.21.6-remote-photon-fips.yaml
  k8s/0.21.6/0.21.6-remote-photon.yaml
  k8s/0.21.6/local/vsecm-distroless-fips.yaml
  k8s/0.21.6/local/vsecm-distroless.yaml
  k8s/0.21.6/local/vsecm-photon-fips.yaml
  k8s/0.21.6/local/vsecm-photon.yaml
  k8s/0.21.6/remote/vsecm-distroless-fips.yaml
  k8s/0.21.6/remote/vsecm-distroless.yaml
  k8s/0.21.6/remote/vsecm-photon-fips.yaml
  k8s/0.21.6/remote/vsecm-photon.yaml
  k8s/0.21.6/spire.yaml
  makefiles/VSecMDeploy.mk
  makefiles/helmUtils.mk
Labels: enhancement

#379 documentation and minor code changes
  app/safe/cmd/main.go
  app/safe/internal/bootstrap/bootstrap.go
  app/safe/internal/bootstrap/privates.go
  docs/_pages/0110-configuration.md
  docs/_pages/0980-release-management.md
  hack/init-next-helm-chart.sh
  hack/release-helm-chart.sh
  helm-charts/0.21.6/Chart.yaml
Labels: dco-required
