Repository vmware-tanzu/secrets-manager, pull requests merged in 2024-01, with the labels that each got.

#388 ability to export secrets in encrypted form
  app/keygen/cmd/decrypt.go
  app/keygen/cmd/generate.go
  app/keygen/cmd/main.go
  app/safe/internal/state/io-decrypt.go
  core/crypto/crypto.go
  core/crypto/decrypt.go
  core/crypto/key.go
  core/crypto/parser.go
  core/crypto/value.go
  core/entity/data/v1/v1.go
  core/entity/reqres/safe/v1/v1.go
  core/env/keygen.go
  dockerfiles/util/keygen.Dockerfile
  examples/operator-decrpyt-secrets/key.txt
  examples/operator-decrpyt-secrets/reveal.sh
  examples/operator-decrpyt-secrets/secrets.json
Labels: dco-required

#401 Updating k8s-manifests and image in helm-chart
  helm-charts/0.22.0/values.yaml
  k8s/0.22.0/local/vsecm-distroless-fips.yaml
  k8s/0.22.0/local/vsecm-distroless.yaml
  k8s/0.22.0/local/vsecm-photon-fips.yaml
  k8s/0.22.0/local/vsecm-photon.yaml
  k8s/0.22.0/remote/vsecm-distroless-fips.yaml
  k8s/0.22.0/remote/vsecm-distroless.yaml
  k8s/0.22.0/remote/vsecm-photon-fips.yaml
  k8s/0.22.0/remote/vsecm-photon.yaml
  k8s/0.22.0/spire.yaml
Labels: enhancement, feature:helm-charts

#407 Better-Commits and Documentation Updates
  .better-commits.json
  .github/PULL_REQUEST_TEMPLATE/pull-request.md
  Makefile
  README.md
  core/env/keygen.go
  core/env/secret.go
  docs/_pages/0070-architecture.md
  docs/_pages/0090-cli.md
  docs/_pages/0110-configuration.md
  docs/_pages/0130-contributing.md
  helm-charts/0.22.0/values.yaml
  makefiles/Git.mk
Labels: dco-required

#421 📚 docs(VSecM): #380 Updating release management doc
  docs/_pages/0980-release-management.md
Labels: documentation

#422 🐛 fix(VSecM): Updating k8s manifests
  k8s/0.22.1/local/vsecm-distroless-fips.yaml
  k8s/0.22.1/local/vsecm-distroless.yaml
  k8s/0.22.1/local/vsecm-photon-fips.yaml
  k8s/0.22.1/local/vsecm-photon.yaml
  k8s/0.22.1/remote/vsecm-distroless-fips.yaml
  k8s/0.22.1/remote/vsecm-distroless.yaml
  k8s/0.22.1/remote/vsecm-photon-fips.yaml
  k8s/0.22.1/remote/vsecm-photon.yaml
  k8s/0.22.1/spire.yaml
Labels: bug

#423 🌟 enhancement(SPIRE): Upgrading spire and spiffee-csi-driver
  helm-charts/0.22.1/values.yaml
  k8s/0.22.1/spire.yaml
Labels: enhancement, maintenance

#434 🐛 fix(VSecM): The current tests were failing
  Makefile
  ci/crontab.txt
  ci/poll/api.go
  ci/poll/env.go
  ci/poll/lock.go
  ci/poll/main.go
  ci/poll/notify.go
  ci/poll/path.go
  ci/poll/pipeline.go
  ci/poll/process.go
Labels: dco-required

#435 🐛 fix(VSecM): update vsecm version in manifests
  docs/_pages/0090-cli.md
  docs/_pages/0980-release-management.md
  examples/federation-workshop/cluster-1/inspector/Deployment.yaml
  examples/federation-workshop/cluster-1/sentinel/Deployment.yaml
  examples/federation-workshop/cluster-2/safe/Deployment.yaml
  examples/multiple-secrets/k8s/Deployment.yaml
  examples/multiple-secrets/k8s/image-override.yaml
  examples/operator-decrpyt-secrets/reveal.sh
  examples/pre-vsecm-workshop/init-container/Deployment.yaml
  examples/pre-vsecm-workshop/init-container/image-override.yaml
  examples/pre-vsecm-workshop/inspector/Deployment.yaml
  examples/pre-vsecm-workshop/inspector/image-override.yaml
  examples/pre-vsecm-workshop/sdk/Deployment.yaml
  examples/pre-vsecm-workshop/sdk/image-override.yaml
  examples/pre-vsecm-workshop/sidecar/Deployment.yaml
  examples/pre-vsecm-workshop/sidecar/image-override.yaml
  examples/using-init-container/k8s/Deployment.yaml
  examples/using-init-container/k8s/image-override.yaml
  examples/using-sdk/k8s/Deployment.yaml
  examples/using-sdk/k8s/image-override.yaml
  examples/using-sidecar/k8s/Deployment.yaml
  examples/using-sidecar/k8s/image-override.yaml
  examples/vsecm-workshop/workloads/example-init-container/Deployment.yaml
  examples/vsecm-workshop/workloads/inspector/Deployment.yaml
  hack/init-next-helm-chart.sh
  hack/release-helm-chart.sh
  helm-charts/0.22.2/README.md
  helm-charts/0.22.2/values.yaml
  k8s/0.22.2/local/vsecm-distroless-fips.yaml
  k8s/0.22.2/local/vsecm-distroless.yaml
  k8s/0.22.2/local/vsecm-photon-fips.yaml
  k8s/0.22.2/local/vsecm-photon.yaml
  k8s/0.22.2/remote/vsecm-distroless-fips.yaml
  k8s/0.22.2/remote/vsecm-distroless.yaml
  k8s/0.22.2/remote/vsecm-photon-fips.yaml
  k8s/0.22.2/remote/vsecm-photon.yaml
  makefiles/VSecMHelmUtils.mk
Labels: dco-required

#449 ✨ feat(SPIRE): Upgrading spire-controller-manager to 0.4.1
  helm-charts/0.22.3/values.yaml
Labels: dco-required

#445 minor fix before a demo
  .github/pull-request-template.md
  app/keygen/cmd/decrypt_test.go
  app/keygen/cmd/generate_test.go
  app/safe/internal/bootstrap/bootstrap_test.go
  app/safe/internal/bootstrap/k8s_test.go
  app/safe/internal/bootstrap/privates_test.go
  app/safe/internal/server/handle/hande_test.go
  app/safe/internal/server/handle/spiffe_test.go
  app/safe/internal/server/route/delete_test.go
  app/safe/internal/server/route/fetch_test.go
  app/safe/internal/server/route/list_test.go
  app/safe/internal/server/route/receive_test.go
  app/safe/internal/server/route/secret_test.go
  app/safe/internal/server/server_test.go
  app/sentinel/cmd/help_test.go
  app/sentinel/cmd/parse_test.go
  app/sentinel/internal/safe/get_test.go
  app/sentinel/internal/safe/post.go
  app/sentinel/internal/safe/post_test.go
  core/crypto/decrypt_test.go
  core/crypto/key_test.go
  core/entity/reqres/safe/v1/v1_test.go
  core/env/keygen_test.go
  core/env/secret_test.go
  core/probe/probe_test.go
  core/system/wait_test.go
  docs/_pages/0070-architecture.md
  docs/_pages/0110-configuration.md
  docs/_pages/0140-production.md
  docs/_pages/0250-showcase.md
  docs/_pages/0260-changelog.md
  examples/federation-workshop/cluster-1/spire/spire/spire-agent.yaml
  examples/federation-workshop/cluster-1/spire/spire/spire-server.yaml
  examples/federation-workshop/cluster-2/spire/spire/spire-agent.yaml
  examples/federation-workshop/cluster-2/spire/spire/spire-server.yaml
  examples/operator-decrpyt-secrets/reveal.sh
  sdk/internal/timer/timer_test.go
  sdk/sentry/fetch_test.go
  sdk/sentry/privates_test.go
  sdk/sentry/watch_test.go
  sdk/startup/watch_test.go
Labels: dco-required
